CREATE TABLE phones (
    id serial primary key,
    name text,
    manufacturer text,
    price numeric,
    units int
);

INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Google', 1439.42, 448);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Google', 1364.04, 464);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Huawei', 1228.01, 340);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Oppo', 1471.95, 330);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'OnePlus', 554.82, 70);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Nokia', 1401.8, 376);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'OnePlus', 1217.27, 113);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Huawei', 841.47, 194);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Oppo', 964.23, 161);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Asus', 967.46, 416);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Google', 1476.26, 151);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Asus', 1365.59, 175);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Sony', 982.07, 300);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Asus', 791.36, 213);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Sony', 607.73, 482);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'OnePlus', 256.63, 436);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Xiaomi', 689.75, 125);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Nokia', 1358.51, 407);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Asus', 1433.95, 162);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Nokia', 1463.64, 60);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Sony', 173.24, 83);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Nokia', 687.04, 406);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Apple', 304.19, 307);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Nokia', 534.67, 411);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'OnePlus', 1036.27, 357);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Samsung', 135.28, 438);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'OnePlus', 409.84, 351);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Huawei', 163.54, 63);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Xiaomi', 828.06, 126);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'OnePlus', 1391.55, 295);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Asus', 363.83, 207);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Huawei', 119.95, 345);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Samsung', 1108.05, 391);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Oppo', 1253.43, 5);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Oppo', 1210.57, 241);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Xiaomi', 1048.74, 405);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'OnePlus', 302.68, 477);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Xiaomi', 473.73, 233);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Xiaomi', 1192.4, 234);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Samsung', 1139.97, 133);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Nokia', 1292.66, 115);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Asus', 576.69, 337);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Apple', 1180.75, 421);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Xiaomi', 868.53, 157);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Samsung', 158.84, 122);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Nokia', 312.0, 246);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Xiaomi', 122.9, 153);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Xiaomi', 168.36, 177);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Google', 850.87, 34);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Oppo', 187.12, 425);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Oppo', 291.51, 163);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'OnePlus', 719.21, 220);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Google', 909.23, 21);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Asus', 795.47, 446);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Sony', 635.02, 463);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Samsung', 1456.14, 480);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'OnePlus', 1371.88, 262);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Apple', 743.48, 245);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Oppo', 1238.22, 221);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Huawei', 297.3, 278);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Google', 892.82, 58);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Google', 336.2, 226);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Oppo', 366.17, 424);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Xiaomi', 1295.39, 64);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'OnePlus', 1082.11, 224);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Samsung', 1224.2, 427);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Xiaomi', 1128.39, 452);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Huawei', 1419.88, 96);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Oppo', 1225.15, 283);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Sony', 978.9, 24);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Nokia', 962.43, 146);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Apple', 1387.07, 198);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Oppo', 386.9, 422);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Apple', 606.03, 258);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Nokia', 612.0, 404);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Huawei', 663.62, 387);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Asus', 283.58, 205);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Oppo', 1324.73, 20);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Google', 1212.49, 210);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Xiaomi', 627.84, 44);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Samsung', 988.11, 460);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Google', 284.28, 488);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Xiaomi', 898.55, 206);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Huawei', 641.62, 301);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'OnePlus', 692.21, 89);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Sony', 745.73, 462);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'OnePlus', 1471.28, 500);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'OnePlus', 1435.14, 177);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Huawei', 1234.84, 307);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Asus', 1186.5, 273);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Xiaomi', 568.76, 297);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Oppo', 1271.77, 372);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Huawei', 571.6, 69);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Asus', 277.58, 419);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Apple', 826.68, 439);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Oppo', 750.37, 286);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Huawei', 1453.57, 463);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Sony', 989.79, 337);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Xiaomi', 230.46, 201);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Samsung', 460.93, 3);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Apple', 741.57, 159);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Google', 1193.72, 451);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Samsung', 1441.77, 78);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Asus', 584.76, 113);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Google', 1463.77, 429);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Oppo', 1359.15, 205);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Oppo', 1461.22, 441);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Google', 174.21, 277);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Nokia', 1432.49, 240);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Asus', 1101.93, 381);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Xiaomi', 227.13, 267);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Asus', 698.59, 154);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Xiaomi', 821.4, 109);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Nokia', 418.84, 109);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Oppo', 651.59, 493);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Xiaomi', 654.48, 129);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Google', 818.51, 208);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Asus', 1266.92, 244);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Huawei', 177.81, 458);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Asus', 923.07, 343);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'OnePlus', 1406.22, 496);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Apple', 1215.41, 169);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'OnePlus', 933.91, 288);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Nokia', 1201.26, 283);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Xiaomi', 1269.53, 487);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Oppo', 211.63, 273);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Nokia', 210.87, 388);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Asus', 1231.46, 328);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Sony', 842.52, 212);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Huawei', 245.5, 74);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Samsung', 553.5, 42);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Asus', 259.34, 256);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Apple', 1058.27, 50);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'OnePlus', 317.78, 438);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Asus', 1277.77, 72);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Apple', 886.61, 90);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'OnePlus', 1067.54, 488);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Nokia', 903.96, 410);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Samsung', 758.53, 82);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Xiaomi', 130.18, 242);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Samsung', 1261.91, 450);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Huawei', 1306.11, 434);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Google', 1423.52, 418);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Sony', 289.2, 393);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Huawei', 1205.63, 241);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Huawei', 187.53, 193);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Apple', 1429.0, 63);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Huawei', 983.97, 387);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Apple', 734.87, 486);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Sony', 1131.21, 372);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Google', 1218.67, 75);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'OnePlus', 409.56, 429);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Apple', 1335.79, 115);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Huawei', 617.94, 66);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Nokia', 986.46, 78);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Xiaomi', 843.52, 428);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Xiaomi', 1150.63, 431);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'OnePlus', 1380.35, 332);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Xiaomi', 488.13, 65);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Apple', 133.03, 60);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Sony', 991.29, 33);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Apple', 1080.3, 86);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Nokia', 446.69, 389);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Asus', 572.13, 204);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Sony', 866.96, 138);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Google', 181.74, 304);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Google', 789.94, 41);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Sony', 800.98, 244);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Nokia', 634.1, 105);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Oppo', 559.0, 110);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Sony', 1137.53, 479);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Samsung', 486.67, 188);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Huawei', 263.36, 329);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Oppo', 864.86, 17);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'OnePlus', 1403.54, 492);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Samsung', 1103.71, 89);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Huawei', 420.21, 258);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Apple', 1231.34, 403);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Samsung', 784.84, 194);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Apple', 920.21, 270);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Samsung', 208.92, 81);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Apple', 1075.5, 20);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Nokia', 1282.51, 318);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Huawei', 395.42, 258);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Google', 1305.89, 36);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Sony', 1272.21, 418);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Huawei', 1301.21, 377);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Xiaomi', 880.27, 191);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Nokia', 1248.25, 419);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Apple', 1475.34, 105);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Huawei', 331.21, 318);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Apple', 907.27, 35);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Huawei', 218.06, 10);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Asus', 654.33, 163);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Xiaomi', 886.76, 101);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Xiaomi', 594.6, 307);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Asus', 957.88, 170);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Google', 676.15, 97);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Asus', 314.81, 322);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Asus', 1334.75, 138);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Google', 913.18, 268);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Google', 177.32, 171);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Nokia', 738.29, 429);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Google', 1286.72, 391);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'OnePlus', 749.97, 96);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Google', 1032.63, 276);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Asus', 1298.49, 220);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Huawei', 859.73, 57);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Samsung', 1041.18, 480);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Huawei', 589.62, 481);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Google', 842.15, 421);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Samsung', 459.54, 62);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Oppo', 620.82, 262);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Asus', 1416.9, 212);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'OnePlus', 171.01, 195);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'OnePlus', 1107.83, 499);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Asus', 1452.84, 41);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'OnePlus', 917.27, 214);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Oppo', 956.38, 474);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'OnePlus', 763.36, 114);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Nokia', 1246.02, 237);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Apple', 283.39, 255);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Huawei', 708.96, 173);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Huawei', 247.34, 448);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Sony', 1017.35, 454);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Samsung', 1161.6, 444);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Oppo', 504.56, 416);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Apple', 639.17, 241);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Oppo', 496.28, 288);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Asus', 125.9, 36);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Samsung', 528.6, 494);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Apple', 651.74, 442);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Samsung', 652.85, 220);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Xiaomi', 1174.69, 301);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Google', 1220.98, 488);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Apple', 1349.13, 46);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Xiaomi', 1173.89, 344);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Sony', 962.23, 171);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'OnePlus', 912.81, 89);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Google', 325.6, 301);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Samsung', 1293.73, 490);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Nokia', 854.47, 138);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Samsung', 805.18, 79);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Xiaomi', 1129.39, 328);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Xiaomi', 1236.12, 404);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Huawei', 246.86, 179);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Asus', 790.24, 16);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Sony', 897.59, 200);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Asus', 1256.2, 149);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Apple', 867.8, 230);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Apple', 298.8, 30);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Google', 204.22, 307);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Apple', 541.52, 5);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Samsung', 138.7, 385);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Nokia', 1098.12, 105);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Oppo', 376.95, 67);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Asus', 1484.03, 453);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Huawei', 1080.8, 153);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Google', 507.24, 295);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Nokia', 149.26, 488);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Asus', 1252.45, 418);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Apple', 635.38, 10);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Oppo', 232.86, 471);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Xiaomi', 618.16, 330);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Xiaomi', 1209.74, 438);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Google', 102.35, 54);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Xiaomi', 115.01, 358);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Apple', 1355.77, 342);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Apple', 780.82, 346);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Google', 1302.5, 183);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Apple', 576.36, 254);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Huawei', 1030.24, 150);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Xiaomi', 362.14, 412);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'OnePlus', 297.67, 406);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Xiaomi', 1342.03, 164);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Oppo', 945.87, 493);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Sony', 1224.61, 28);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Nokia', 257.53, 289);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Nokia', 1352.34, 118);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Xiaomi', 1136.34, 97);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Huawei', 1382.63, 442);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Sony', 1245.52, 391);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Xiaomi', 982.07, 51);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Xiaomi', 1187.16, 408);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Oppo', 360.2, 445);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'OnePlus', 1469.69, 9);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Sony', 580.48, 370);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Apple', 851.11, 96);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Sony', 846.21, 23);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Xiaomi', 674.97, 107);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Asus', 1442.36, 214);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Asus', 889.71, 321);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Oppo', 294.42, 35);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Nokia', 775.51, 92);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Sony', 1410.37, 110);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Apple', 813.57, 29);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Huawei', 239.21, 461);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Apple', 1439.72, 143);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Sony', 820.78, 392);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Asus', 486.57, 246);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Nokia', 385.49, 133);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Sony', 971.17, 76);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Huawei', 214.5, 38);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Sony', 896.49, 328);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Apple', 1197.22, 144);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Huawei', 599.71, 473);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Sony', 1278.82, 335);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Google', 115.9, 373);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Huawei', 111.88, 342);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Oppo', 592.59, 244);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Google', 1399.06, 73);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Sony', 622.35, 352);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Google', 1440.85, 113);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Sony', 234.18, 110);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Google', 1404.34, 234);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Nokia', 818.22, 278);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Sony', 753.22, 275);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Xiaomi', 1413.32, 334);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Oppo', 436.88, 399);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Oppo', 1064.55, 219);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Xiaomi', 678.04, 109);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Apple', 1222.3, 338);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Xiaomi', 972.55, 292);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'OnePlus', 1173.9, 199);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Xiaomi', 329.74, 426);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Huawei', 1389.72, 400);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Google', 1486.98, 485);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'OnePlus', 882.24, 79);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Xiaomi', 782.26, 263);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Huawei', 928.14, 342);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Google', 224.57, 70);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Asus', 567.15, 287);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Samsung', 1302.05, 130);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Oppo', 1341.39, 208);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Oppo', 950.39, 150);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Asus', 1151.27, 384);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Nokia', 748.26, 324);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'OnePlus', 710.84, 41);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'OnePlus', 493.35, 234);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Oppo', 1271.59, 439);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Oppo', 723.19, 271);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Asus', 604.18, 441);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'OnePlus', 215.29, 259);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Sony', 718.41, 89);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Samsung', 455.55, 205);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Google', 318.03, 151);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Apple', 315.49, 475);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Samsung', 1331.54, 353);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Oppo', 1397.45, 47);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Sony', 636.75, 329);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Apple', 110.39, 418);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Asus', 596.26, 199);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Apple', 1377.29, 176);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Xiaomi', 1352.05, 211);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Huawei', 1144.94, 187);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Nokia', 969.34, 328);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Sony', 1131.95, 152);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Nokia', 1142.96, 310);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Oppo', 482.37, 206);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'OnePlus', 382.3, 277);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Nokia', 300.87, 425);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Apple', 1405.21, 181);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Apple', 970.81, 476);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Oppo', 1084.95, 43);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Nokia', 1145.5, 439);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'OnePlus', 1325.86, 311);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Xiaomi', 697.03, 204);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Oppo', 1455.96, 61);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Xiaomi', 507.11, 343);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Huawei', 1334.77, 348);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Google', 998.95, 149);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Nokia', 1321.56, 46);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Google', 633.4, 248);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Nokia', 1427.01, 68);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'OnePlus', 1207.84, 365);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Google', 310.56, 264);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Google', 1097.89, 9);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Apple', 400.21, 385);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Google', 922.25, 425);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Sony', 1317.32, 352);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'OnePlus', 242.79, 328);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Sony', 1141.62, 353);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Nokia', 175.12, 57);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Nokia', 1349.53, 352);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Huawei', 408.23, 362);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Apple', 400.84, 339);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Oppo', 744.31, 48);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Apple', 1484.24, 478);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Huawei', 586.87, 114);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Google', 410.11, 361);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Apple', 1340.47, 410);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Oppo', 902.17, 274);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Samsung', 724.69, 423);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Sony', 526.5, 474);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Nokia', 318.26, 109);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Google', 468.64, 29);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Samsung', 373.71, 487);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Asus', 136.06, 172);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Asus', 197.93, 199);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Asus', 323.74, 405);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Apple', 1313.15, 45);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Google', 650.83, 372);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Samsung', 680.76, 499);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Apple', 1092.19, 424);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Asus', 1275.26, 393);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Sony', 552.41, 260);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Samsung', 689.05, 208);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Nokia', 471.46, 102);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Asus', 1322.78, 269);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Samsung', 1105.47, 165);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Asus', 838.76, 145);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Apple', 444.2, 215);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Nokia', 1163.76, 430);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Asus', 354.32, 73);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Google', 176.98, 467);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Samsung', 144.3, 219);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Nokia', 644.31, 107);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Google', 318.71, 371);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'OnePlus', 968.69, 73);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'OnePlus', 1446.9, 5);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Apple', 698.16, 421);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Samsung', 655.23, 130);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Google', 1268.91, 11);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Oppo', 923.31, 116);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Sony', 936.46, 341);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Sony', 217.55, 222);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Sony', 1247.91, 473);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Xiaomi', 1424.65, 341);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Samsung', 1059.54, 114);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Oppo', 1093.12, 114);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Huawei', 967.91, 410);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Apple', 920.98, 350);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Google', 320.29, 381);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Nokia', 957.3, 428);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Nokia', 1154.97, 52);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Xiaomi', 215.77, 463);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Sony', 622.31, 438);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'OnePlus', 218.98, 388);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Oppo', 484.94, 322);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Huawei', 1203.93, 230);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Google', 596.61, 440);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Apple', 1091.36, 278);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Apple', 178.13, 157);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Samsung', 230.43, 399);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Samsung', 597.65, 40);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'OnePlus', 1030.09, 176);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Apple', 999.34, 9);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'OnePlus', 322.62, 122);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Samsung', 1451.55, 280);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'OnePlus', 252.16, 329);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Asus ROG Phone 5', 'Apple', 430.26, 458);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Huawei', 1404.63, 452);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Xiaomi', 1132.61, 277);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Nokia', 632.42, 197);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'OnePlus', 122.41, 488);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Sony', 102.88, 378);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Xiaomi', 663.7, 278);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Huawei', 1474.97, 23);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Apple', 968.76, 12);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'OnePlus', 575.9, 304);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Samsung', 543.47, 133);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Huawei', 436.45, 52);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Google', 359.42, 166);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Xiaomi', 1051.6, 62);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Oppo', 536.46, 74);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Xiaomi', 339.56, 191);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Apple', 165.02, 430);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'OnePlus', 429.0, 459);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Samsung', 314.03, 172);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Huawei', 653.83, 379);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Nokia', 758.48, 307);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Asus', 996.77, 261);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Apple', 1260.1, 500);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Google', 136.02, 46);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'Samsung', 1457.99, 221);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Nokia', 1228.61, 390);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Samsung', 1127.4, 239);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Nokia', 1084.96, 458);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Sony', 695.31, 51);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Samsung', 179.82, 7);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Oppo', 1230.19, 313);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'OnePlus', 398.15, 202);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Sony Xperia 5', 'OnePlus', 564.34, 33);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Xiaomi', 1407.07, 203);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('OnePlus 9', 'Huawei', 997.46, 298);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Asus', 1043.08, 63);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Asus', 1167.94, 500);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Nokia 8.3', 'Nokia', 547.05, 281);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Apple', 518.64, 352);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Oppo', 932.84, 334);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Samsung Galaxy S21', 'Apple', 109.44, 393);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Asus', 577.25, 167);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Samsung', 838.24, 382);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Asus', 1396.75, 230);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Huawei P40', 'Asus', 948.3, 207);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'OnePlus', 1031.99, 384);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('iPhone 12', 'Nokia', 1309.3, 231);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Xiaomi Mi 11', 'Asus', 472.37, 80);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Google Pixel 5', 'Huawei', 677.14, 67);
INSERT INTO phones (name, manufacturer, price, units) VALUES ('Oppo Find X3', 'Asus', 198.14, 164);
